import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Navbar from '@/components/Navbar';
import { CartProvider } from '@/app/cart/CartProvider';
import { CartDrawer } from './cart/CartDrawer';
import { getSessionUser } from '@/lib/authz';
import { getCartItems } from './services/data';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Maison Store',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getSessionUser();
  const cartItems = user ? await getCartItems(user.sub!) : [];
  return (
    <html
      lang='en'
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className='min-h-full flex flex-col'>
        <CartProvider>
          <Navbar />
          <CartDrawer cartItems={cartItems} />
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
